### ISSUE TITLE
Odd behaviour with onoremap and zv

### ISSUE THREAD

**Issue by spiiph** [spiiph/vim-space#1]
graywh reported some odd behaviour with operator pending mappings and foldopen-emulation using zv when the operator would enter insert mode. I.e., c<Space> enters insert mode and the text 'zv', rather than issuing the actual command.

**Comment by graywh** [comment]
On a related note:

Do ":set all" or something else  and press : at the "-- More --" prompt to get to the command line.  "zv" is printed there.

**Comment by spiiph** [comment]
This zv business is a can of worms! Thanks.

**Comment by spiiph** [comment]
Issue was fixed by @kongo2002 in revision 9aab26c2.
