### ISSUE TITLE
Remapping ; to : does not take effect

### ISSUE THREAD

**Issue by casey-chow** [spiiph/vim-space#14]
When I installed this plugin, I found that my remapping of `:` to `;` did not work.

My remapping of `;` to `:` did work however. I assume the problem is that Space is hooking into the `;` key.

The commands I used in my vimrc:

```
nnoremap ; :
nnoremap : ;
```

**Comment by spiiph** [comment]
It might, since space.vim is probably loaded after .vimrc. Either put 

let g:space_no_character_movements = 1

in your .vimrc, to disable <Space> for fFtT;, movements altogether, or make sure that space.vim is loaded before you add that mapping.
