### ISSUE TITLE
Default map for SmartSpacePrev does not work in terminal Vim

### ISSUE THREAD

**Issue by blueyed** [spiiph/vim-space#22]
The problem is that `<S-Space>` is not recognized by Vim in a terminal.

See also http://stackoverflow.com/questions/279959/how-can-i-make-shiftspacebar-page-up-in-vim .

**Comment by spiiph** [comment]
In terminal Vim, `<BS>` is the default map for the inverse movement.

https://github.com/spiiph/vim-space/blob/master/plugin/space.vim#L104
