### ISSUE TITLE
weird count stuff

### ISSUE THREAD

**Issue by graywh** [spiiph/vim-space#3]
4dd<Space> results in the count 4 being used for the <Space> command, too.

**Comment by spiiph** [comment]
Odd. I wonder if it's remembered in the v:count variable somehow. I'll look into it.

**Comment by spiiph** [comment]
I cannot reproduce this behaviour. Do you have exact instructions on how to reproduce? 

The v:count is not duplicated by <Space>, i.e. 4n<Space> will equal 5n, not 8n. v:count can be used as 4<Space> though. I don't see how v:count can be remembered, since it's not really detected.

**Comment by graywh** [comment]
I'm not seeing it either, now.  ::shrug::
