### ISSUE TITLE
<bs>

### ISSUE THREAD

**Issue by kurkale6ka** [spiiph/vim-space#5]
Hi,
I have backspace mapped to "_X.
Could you make optional the use of backspace as a synonym to shift-space?
Cheers

**Comment by spiiph** [comment]
Hi,
I'll add a hasmapto() check, and see if I can add optional mappings too. It won't happen too soon, though.

**Comment by spiiph** [comment]
Fixed in eb2492c. Added a mapcheck() to avoid overriding other remappings of <BS> when using the GUI. When using terminal Vim, <BS> is always mapped since <S-Space> cannot be used.
