### ISSUE TITLE
Issue when using tpope's flatfoot.vim plugin

### ISSUE THREAD

**Issue by kurkale6ka** [spiiph/vim-space#6]
Hi,
I will raise this issue with tpope as well as I am not sure where it should be fixed.
The issue is: in gvim (7.3.46) only: when using both plugins, the f / t mappings won't work for one
or the other plugin depending on which one is sourced first.
Cheers

**Comment by spiiph** [comment]
I suggest using 'let g:space_no_character_movements' to disable space.vim's mappings of f and t.
