### ISSUE TITLE
noremap setup_space("jump", "\<c-i>") problem

### ISSUE THREAD

**Issue by kurkale6ka** [spiiph/vim-space#7]
Hi,
Could you change this map to nnoremap because it kills my:
xmap <tab> >
Cheers

**Comment by spiiph** [comment]
Right. &lt;C-o&gt; and &lt;C-i&gt; are not motions, and cannot be used in visual mode. I'll change this.

**Comment by spiiph** [comment]
Fixed in 2d7a39d.
